PermitRootLogin no
PasswordAuthentication no
KbdInteractiveAuthentication no
PubkeyAuthentication yes
AuthenticationMethods publickey
PermitEmptyPasswords no
MaxAuthTries 4
LoginGraceTime 60
X11Forwarding no
AllowUsers moutsss alice bob
Banner /etc/issue.net
ClientAliveInterval 600
AllowTcpForwarding no
